apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-nodejs
  template:
    metadata:
      labels:
        app: devops-nodejs
    spec:
      containers:
        - name: nodejs-app
          image: devops-nodejs-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          # Readiness Probe
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
