apiVersion: v1
kind: Service
metadata:
  name: devops-nodejs-service
spec:
  type: NodePort
  selector:
    app: devops-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
